config/routes.rb
Rails.application.routes.draw do
  get 'posts/user/:username' => 'posts#posts_by_user'
  resources :posts
  get 'feed' => 'posts#get_feed'
  root to: 'pages#home'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'login' => 'pages#login'
  get 'u/:username' => 'pages#profile'
  get 'profile/edit' => 'pages#edit_profile'
  get 'user-data/:user_id' => 'application#get_user_data'
  get 'explore' => 'pages#explore'
  post 'profile/edit' => 'profile#edit'

  post 'profile/edit' => 'profile#edit'

  post 'follow' => 'following#follow'

end

app/views/pages/_dashboard.html.erb
<section id="main" class="dashboard">
<div class="columns">
    <%= render 'profile-card',  user: current_user%>
    <section class="column">
        <div id="new-tweet">
            <div class="box" id="tweet-box">
                <%= form_with model: @post, format: :json, :remote => true do |form| %>
                    <% if @post.errors.any? %>
                        <div id="error_explanation">
                        <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

                        <ul>
                        <% @post.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                        <% end %>
                        </ul>
                        </div>
                    <% end %>

                    <div class="control">
                        <textarea class="textarea" placeholder="Share your thoughts!" name="content" id="content"></textarea>
                    </div>
                    <div class="field is-grouped is-grouped-right">
                        <div class="control">
                            <button class="button is-primary" type="submit">Submit</button>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
        <div id="posts">
        </div>
    </section>
</div>

</section>
<%= javascript_include_tag '/javascripts/pages__dashboard', defer: true %>

app/views/pages/_profile-card.html.erb
<section class="column is-one-quarter">
    <div class="box">
        <% unless user.nil? %>
            <article class="media">
                <div class="media-content">
                    <div class="content">
                        <figure class="image">
                            <% if user.profile_picture.attached? %>
                                <div class="profile-image main-profile-image" style="background-image: url(<%= url_for(user.profile_picture)%>);"></div>
                            <% else %>
                                <img src="https://bulma.io/images/placeholders/128x128.png" alt="Image" class="is-rounded">
                            <% end %>
                        </figure>
                        <article class="media">
                            <a class="media-left" href="/u/<%= user.username %>" target="_blank">
                                <strong><%= user.fullname %></strong>
                                <br>
                                <small>@<%= user.username %></small>
                                <br>
                            </a>
                            <% if current_user != user %>
                                <% if current_user %>
                                <form action="/follow">
                                    <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
                                    <input name="user_id" value="<%= user.id %>" type="hidden">
                                    <button type="submit" class="button is-primary media-right" id="follow_button">
                                        <% if current_user.followees.exists?(user.id) %>
                                            <%= 'Unfollow' %>
                                        <% else %>
                                            <%= 'Follow' %>
                                        <% end %>
                                    </button>
                                </form>
                                <% end %>
                            <% else %>
                                <a href="/profile/edit">Edit Profile</a>
                            <% end %>
                        </article>
                    </div>
                </div>
            </article>
        <% end %>

        <article class="media">
            <article class="media-left">
                <h3>Following</h3>
                <span><%= user.followees.size %></span>
        </article>
            <article class="media-right">
                <h3>Followers</h3>
                <span><%= user.followers.size %></span>
            </article>
        </article>
    </div>
</section>

app/views/pages/_registration.html.erb
<section id="main" class="home auth">
  <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
    <div class="tagline">
      <span>Be part of a growing, like-minded community.</span>
      <h1>Your community</h1>
    </div>
    <label for="username" required>Username</label><br/>
    <input name="username" id="username">
    <label for="password">Password</label><br/>
    <input name="password" id="password" type="password" required minlength="6">
    <label for="password_conf">Re-type Password</label><br/>
    <input name="password_conf" id="password_conf" type="password" required minlength="6">
    <div class="button-area">
      <button id="registration_submit_button" type="submit">REGISTER</button>
    </div>
  <%end%>
</section>
<%= javascript_include_tag '/javascripts/pages__home', defer: true %>

app/views/pages/edit_profile.html.erb
<section id="main" class="profile-edit">
    <div class="columns">
        <div class="column is-half is-offset-one-quarter">
            <div class="box">
                <h2 class="is-size-5">Edit your profile</h2><br>
                <form action="" method="post">
                        <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">                    <div class="field is-horizontal">
                        <div class="field-label is-normal">
                            <label class="label">Full name</label>
                        </div>
                        <div class="field-body">
                            <div class="field">
                            <p class="control">
                                <input class="input" type="text" name="fullname" id="fullname" placeholder="Your full name here" value="<%= current_user.fullname %>">
                            </p>
                            </div>
                        </div>
                    </div>
                    <div class="field is-horizontal">
                        <div class="field-label is-normal">
                            <label class="label">Profile Picture</label>
                        </div>
                        <div class="file has-name is-fullwidth field-body">
                            <label class="file-label">
                                <input class="file-input" type="file" name="profile_picture" id="profile_picture">
                                <span class="file-cta">
                                <span class="file-icon">
                                    <i class="fas fa-upload"></i>
                                </span>
                                <span class="file-label">
                                    Choose a file…
                                </span>
                                </span>
                                <span class="file-name">
                                </span>
                            </label>
                        </div>
                    </div>
                    <div class="field is-grouped is-grouped-right">
                        <div class="control">
                            <button class="button is-primary" type="submit">Save</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</section>
<%= javascript_include_tag '/javascripts/pages__edit_profile', defer: true %>

app/views/pages/explore.html.erb
<section id="main" class="dashboard">
<div class="columns">
    <%= render 'profile-card',  user: current_user %>
    <section class="column">
        <div id="posts">
        </div>
    </section>
</div>

</section>
<%= javascript_include_tag '/javascripts/pages__explore', defer: true %>

app/views/pages/home.html.erb
<% if user_signed_in? %> 
  <%= render partial: 'dashboard' %>
<% else %>
  <%= render partial: 'registration' %>
<% end %>

app/views/pages/login.html.erb
<section id="main" class="login auth">
  <%= form_for resource, url: session_path(:user), remote: true do |f| %>
    <h2 class="is-size-2">Login</h2>
    <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
    <label for="username" required>Username</label><br/>
    <input name="username" id="username">
    <label for="password">Password</label><br/>
    <input name="password" id="password" type="password" required>
    <div class="button-area">
      <button type="submit">LOG IN</button>
    </div>
  <%end%>
</section>

app/views/pages/profile.html.erb
<section id="main" class="dashboard">
<div class="columns">
    <%= render 'profile-card',  user: @profile_user %>
    <section class="column">
        <div id="posts">
        </div>
    </section>
</div>

</section>
<%= javascript_include_tag '/javascripts/pages__profile', defer: true %>